# scalar JSON
scalar URL
scalar DateTime
scalar Email
scalar UnsignedFloat

type Query {
  _: Boolean
}
type Mutation {
  _: Boolean
}
type Subscription {
  _: Boolean
}

enum PageOrder {
  ASC
  DESC
}

type PageInfo {
  endCursor: String
  hasNextPage: Boolean!
}

input PageInput {
  cursor: String
  order: PageOrder
  limit: Int
}
