directive @requireUser(
  hasPaymentMethod: Boolean
  hasPaymentPayoutMethod: Boolean
) on OBJECT | FIELD_DEFINITION

interface UserI {
  id: String!
  name: String!
  photoUrl: URL
}

type User implements UserI {
  id: String!
  name: String!
  photoUrl: URL
}

type UserPrivate implements UserI {
  id: String!
  name: String!
  photoUrl: URL
}

extend type Auction {
  creator: User!
}

extend type Bid {
  creator: User!
}

extend type Query {
  me: UserPrivate
}
