input JoinWaitListDataInput {
  email: Email!
}

input QueryWaitListInput {
  credentials: String!
}

type WaitListNode {
  email: Email!
  createdAt: DateTime!
  updatedAt: DateTime!
}

extend type Query {
  queryWaitList(data: QueryWaitListInput): [WaitListNode!]
}

extend type Mutation {
  joinWaitList(data: JoinWaitListDataInput!): Boolean
}
