substitutions:
  _ENABLE_PLAYGROUND: 'true'
  _FIREBASE_DATABASE_URL: 'https://yeaap-1.firebaseio.com'
  _FIREBASE_APP_CONFIG: '{}'
  _REDIS_URL: 'redis://localhost:6379'
  _API_URL: 'http://localhost:5000/graphql'
  _WEBSOCKET_URL: 'ws://localhost:5000/graphql'
  _APP_URL: 'http://localhost:5000'
  _SESSION_SECRET: 'something'
  _FIREBASE_CREDENTIALS: '{}'
  _FIREBASE_WEBAPI_KEY: ''
  _GOOGLE_MAPS_KEY: ''
  _STRIPE_API_PUBLISHABLE_KEY: ''
  _STRIPE_API_SECRET_KEY: ''
steps:
  - id: 'create .env file'
    name: 'ubuntu'
    args:
      - bash
      - -c
      - |
        touch .env &&
        echo "ENABLE_PLAYGROUND=$_ENABLE_PLAYGROUND" >> .env &&
        echo "FIREBASE_DATABASE_URL=$_FIREBASE_DATABASE_URL" >> .env &&
        echo "FIREBASE_APP_CONFIG=$_FIREBASE_APP_CONFIG" >> .env &&
        echo "REDIS_URL=$_REDIS_URL" >> .env &&
        echo "API_URL=$_API_URL" >> .env &&
        echo "WEBSOCKET_URL=$_WEBSOCKET_URL" >> .env &&
        echo "APP_URL=$_APP_URL" >> .env &&
        echo "SESSION_SECRET=$_SESSION_SECRET" >> .env &&
        echo "FIREBASE_CREDENTIALS=$_FIREBASE_CREDENTIALS" >> .env &&
        echo "FIREBASE_WEBAPI_KEY=$_FIREBASE_WEBAPI_KEY" >> .env &&
        echo "GOOGLE_MAPS_KEY=$_GOOGLE_MAPS_KEY" >> .env
        echo "STRIPE_API_PUBLISHABLE_KEY=$_STRIPE_API_PUBLISHABLE_KEY" >> .env
        echo "STRIPE_API_SECRET_KEY=$_STRIPE_API_SECRET_KEY" >> .env
  - id: 'deploy to app engine'
    name: 'gcr.io/cloud-builders/gcloud'
    args:
      - app
      - deploy
      - --version=production
timeout: 1840s
