substitutions:
  _ENABLE_PLAYGROUND: 'true'
  _FIREBASE_DATABASE_URL: 'https://yeaap-1.firebaseio.com'
  _FIREBASE_APP_CONFIG: '{}'
  _REDIS_URL: 'redis://localhost:6379'
  _API_URL: 'http://localhost:5000/graphql'
  _WEBSOCKET_URL: 'ws://localhost:5000/graphql'
  _APP_URL: 'http://localhost:5000'
steps:
  - id: 'create .env file'
    name: 'ubuntu'
    args:
      - bash
      - -c
      - |
        touch .env &&
        echo "ENABLE_PLAYGROUND=$_ENABLE_PLAYGROUND" >> .env &&
        echo "FIREBASE_DATABASE_URL=$_FIREBASE_DATABASE_URL" >> .env &&
        echo "FIREBASE_APP_CONFIG=$_FIREBASE_APP_CONFIG" >> .env &&
        echo "REDIS_URL=$_REDIS_URL" >> .env &&
        echo "API_URL=$_API_URL" >> .env &&
        echo "WEBSOCKET_URL=$_WEBSOCKET_URL" >> .env &&
        echo "APP_URL=$_APP_URL" >> .env &&
        echo "FIREBASE_CREDENTIALS=$$FIREBASE_CREDENTIALS" >> .env &&
        echo "FIREBASE_WEBAPI_KEY=$$FIREBASE_WEBAPI_KEY" >> .env &&
        echo "GOOGLE_MAPS_KEY=$$GOOGLE_MAPS_KEY" >> .env
        echo "STRIPE_API_PUBLISHABLE_KEY=$$STRIPE_API_PUBLISHABLE_KEY" >> .env
        echo "STRIPE_API_SECRET_KEY=$$STRIPE_API_SECRET_KEY" >> .env
    secretEnv:
      - FIREBASE_CREDENTIALS
      - FIREBASE_WEBAPI_KEY
      - GOOGLE_MAPS_KEY
      - STRIPE_API_PUBLISHABLE_KEY
      - STRIPE_API_SECRET_KEY
  - id: 'deploy to app engine'
    name: 'gcr.io/cloud-builders/gcloud'
    args:
      - app
      - deploy
      - --promote
      - --stop-previous-version
secrets:
  - kmsKeyName: projects/yeaap-1/locations/global/keyRings/env-variables/cryptoKeys/firebase-credentials
    secretEnv:
      FIREBASE_CREDENTIALS: CiQAcesVzDlE7dEXFftzK2ZmBhBbRAmZESbTkY/WYTnz3D72kAQSnBIAvlY5x5N0knTwtAwo2do7cCazWW9vP+CT8W1fIdUGejNoId13mSvUlmQRWgomQOdheIMlXvTPpZlmW+PRgw7x5k8kGP24ZkmpISWkenRmLf5FQ9DMhLL2iw7tAVQqI5hRhEFgIf66VMuSQNQy/9e25A+ce0RpIxfWMLvpDGWkGZBRLdX25ijWZDk8rcR8aZuoCeKPBAo5A9URqO4xmhgJ7fGQWEMNDSEctdR/70AC2TiO5VFZR/cVaw0LzLCPfk6o43HGZ3CcJ68jqN+qU71ooA+M8iPkQRvSUmm7CMb+jIt4wOJ3+2c/nkJPe+BzDaga2azwrBm/sTwFi610CzFOl4fz2WmVuv/QuCFmwn6oD1ma0ShgAMHB/uh4VujpuZwACLDF/KZTGzVP02REB4EP6cXQCTNhYrAjLaV1lT/bPVejFJLXyv4jA5YiRu+NImFpA9F4E41X0uKnRsI+QIBbwEYXR4p1CZcbKIKu3djSSCHl6pU4bcz5A2zSNdzTtduJk8TsI70VecBULAGSaO/Lb4x88Xo+I8Q+IBUNeltwETsjm+kGn3M/eqMATlMELkXeOx5ZN85/fmoQ9NSS3jRE6DcOx6DEBoy0LxAovGYKMhIt67lNu0A1jcpdPUD3WPnDZTK4mMz1TDHJbIFlmTi0G6qGTgpdMof6G/m+6u1bl87ug8ZW0QIG2u6+1qq9YGaVUOfFIiYZywkctu1dFb38Cwq6rQbLiE4fKE3UAk+vWWCIYnAKTG0J25TiAk58uO3L2ok64ZJlz7Xut1y/obQev8dcIIphIK4CxmnSWKN5nbhnU4oXzqIOPkQWxN9890u+RI/9Km8YqIgRrb1JXIXXnZBEsL7i8kM0aCXi9k1dO7JrTH56qq6IIGczViE0sycmn30gZ8FFW93vvM6zvfRRAg/7aamNykofD2DtzCqwK3tSWcKu2sKHw0f9UrTBXSBpPhmCUdWmpHVGjTFtlL5ZNTMVANNQuEju+dAlGsVXe73QHCDX2+Zr70HDhfrYkv6BCgmluyjN6hqC6H4eKexgEQLyRnnhSb+zTeWddU9kmNIRUOEdOgbph58MV0iSXVXPLQuUhrRY7gd1VJOViUyp7P2yI/Q/7azOaH0HCX6/v7IlguTwgab1V9SxzMj5sfYs/oNZ4W0Qb7SGd1GT8tEV7NS4+UxCcdLwjJc1jR1oaIXvfQcs3KLUEz153ZTAOMM0oz5EtNcSSvc6xexpsEo3C5b4PzL+g7nobVdpWMtYGb5QcWu2b7qK/hIL8Q/iD7RQDdBT+xViB2zjgd9ZYbNspnjKeCvxgxnId6bMQoNTlTzo9+7mFGDOE6cXTRv/0q4P8FfWWakLW5LLYtTkJQ/S6QKCYAnTS3gkemOc7K/5S+lC9YrgOOL3Csk0/gTZI5/k4+DUqSyWpTiAvBhH5ybp0DGk1+XPQbRrXpKiOT0naXMyExEtO2wLK3twyKUWoAqVxTqLc0ReI8U02u7P9qIDmV+2OpEf4Ogsr0i8wkhTi6kbaXXHbZZENmfCmB5ZV9vvHFVeU510Dtpd4NjiHkSZrRsVVp4QZevyPPOfOCrhDUBTy3Pj1SjV22rw/4NNxNXxD2GroOIUgMkorZLjUUUaQiqpbDgBjID5oLlTtNAjkOavXVAiZWFSENewKxYk4amKGp8EHaHQCJnuP65RQcVR9eFZwXhvvaSZ5KsiWu0rpF7iiKPZ1h04BvO6F1VumitVZjF2pMFXB4KpyeJJ9pvxmRuu/MzIPTbdG1DrNPCtpjpYZ604RCaKedn7jVPuuk40fg8kkchX68w6iyo1EyAyTfvCmVIOTeq6bpHPF1W9a6i1JH3W3qFp0IGvwOl6uH479vIgDh4H5h9SrfEKPK3mjpt8D5bkfZJM6xmd7VHEW62x90xzz2ey/cgf3peQTPeoK5aRGt1Ldw6/GXAK0DNhNa8E09gyedgRW6Cf9xUmzsayYt4ai1rtqHO8a0LFDfIVdh02Dy/f0kdkh4AMHMmGzn0pCv3bEoJz1WopJqtsYTcC+BuWEJ0Uf8L0Fdn9u9YlOuhxaM0fedrBOHegQXoLnCtTiSG1Hb8tCmEyqMr7WffE8Kr9UR0jFC2X2FYiSmdHrF0aebPjPtuESUZRoVT5QOY4FhvUdezgIt9o5J4hTO4elOarBmNTPdMCzUqxZQtHar3Qb1gJL8d+PeYXATHzJRfVg+MzXCNelIT4W1nq6pUHqQDZjLXFT8ENcFJQAmWDcoRfzV7Oohe4QJLn7MnYL4i7Nj9jQg+WP2edckj6TxZYQBLiuPa8vLwAEjZoIFRXQfrohTMcMZCN0ml8DELglwmOCYZQwl37i6Mk2tj49Y+uaiveomXGLK18eS6Yc/t3L1OWRgP2RT5565/I6Ch8kFR5j30WzHg73SzRC9oZBqFqx9nDldH6vqAzb6t4xVyyuCky1pnO2ikM7hlmgwjRJF4AGgnp6OCAgetoQKfZCcg2WlU+dtcpU0/mm719LuuSa/sXAOAG6r14DmW7/uThsbqc7MEIQT9JuYaOCnOWFprfIPYhVCwY3HN+ddPL9AYoHTsIqNxteo4qWWtHf9TeybMW+YrpknutUoYWdPNV6qILgeOhzEB8BVNah0hVv33ldTa7dLZtoKEbkkajCkhM/ha4lzJf/eNnYH7X8aFD/hjLkTVpXbe9KMr+tbg70HVoG7ImGJnZtQHMEm6ol68P6VysBYQFMJXXhRPv/atu8sMZUfY1HbgGYo5nafgLq5YlRFRHmABo1QHP5UphXkll0WKXKJWIYb8oKOVrGWyEzG5P6we8bG0wNWyP2w/1PUiT+FCAcPHBzrs3WrpuBAhB4ZE0Wt44LFZHGp+o/q3a/LDl1ItCDRgCM181POT3qipzASAS1cqE56DB3IgC60aWQ9BTFhqDqANsNo6m/EXXwmxDX2vS++jrJStduArFTfUChcxQ9eEuyPCqivc8fkYtIBtbI1CcDZmdzTDoDDM1QYlbj4/kuuvqxwYUv3Wt5w1k50ycnB3uyjbVco7FOhZAjcAaIQy0UKYhVf0j84+PHp8Az2Ig9i/RVx+1SMbj4HTigpJW+QERIdqBJLPXHmGe/KMNrFdx1wYjxYHO
  - kmsKeyName: projects/yeaap-1/locations/global/keyRings/env-variables/cryptoKeys/firebase-webapi-key
    secretEnv:
      FIREBASE_WEBAPI_KEY: CiQARCaVke2VlmpqEsx2ZYIdDay9OWYGc4rzqWCT+iZ9JpEjUn4SUABZpZ8EJGOCkThOWUBP1fBGSrJn9ST5aoKRRj4d2e2o8KlEBLhZ4J6UVz1w1WCb3YUCuOtKd/53xMTYwJXlWtl8rVcWStDtrt3mWdLExaG5
  - kmsKeyName: projects/yeaap-1/locations/global/keyRings/env-variables/cryptoKeys/google-maps-key
    secretEnv:
      GOOGLE_MAPS_KEY: CiQAnP1gZeUPkX5HTxwI7DD8vhOFqF07+KxS6fbcxCF9QssMsuoSUAAmCfnp9AZ91gfluM3i0XsxJdkOJxIKwbQtwNEG844C02n7MhbrT3vFIU70+lEPzkx1haWM8/BCJNz2bnmkcwgayKyAI+ZQgdzJQR/y5evy
  - kmsKeyName: projects/yeaap-1/locations/global/keyRings/env-variables/cryptoKeys/stripe-api-publishable-key
    secretEnv:
      STRIPE_API_PUBLISHABLE_KEY: CiQAstlE+bXdV8z4mi6hpQSxpQnSHDgZParY96BX4bzxgzxxvU0SSQAOkSvmKBvm+zBGoJbet6H0Fc8dQyf8mBqSh70gkluzhOnIb3M0P6t0kO4dlv1ohz0TSHENglqIbybUXiimwR5O++YbglQsda4=
  - kmsKeyName: projects/yeaap-1/locations/global/keyRings/env-variables/cryptoKeys/stripe-api-secret-key
    secretEnv:
      STRIPE_API_SECRET_KEY: CiQAx/bbl99aOTbC1yKo8wSpTXTQhWWYo3ed7gznl303/Np3pGoSSQCJdZflh227DqUV1Z6Oq1WuWWhxLPsU8bFTytDUbzS2ShmKBoqTIRBnKHW3OjiSpTIpC+BxskgyFSgAyU+nkRDuKf30woCiRoQ=
timeout: 1840s
